//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteCancion.CancionSW {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class cancion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int duracionField;
        
        private System.DateTime fechaLanzamientoField;
        
        private bool fechaLanzamientoFieldSpecified;
        
        private string generoField;
        
        private int idField;
        
        private string nombreArtistaField;
        
        private string tituloField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int duracion {
            get {
                return this.duracionField;
            }
            set {
                this.duracionField = value;
                this.RaisePropertyChanged("duracion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fechaLanzamiento {
            get {
                return this.fechaLanzamientoField;
            }
            set {
                this.fechaLanzamientoField = value;
                this.RaisePropertyChanged("fechaLanzamiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaLanzamientoSpecified {
            get {
                return this.fechaLanzamientoFieldSpecified;
            }
            set {
                this.fechaLanzamientoFieldSpecified = value;
                this.RaisePropertyChanged("fechaLanzamientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string genero {
            get {
                return this.generoField;
            }
            set {
                this.generoField = value;
                this.RaisePropertyChanged("genero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombreArtista {
            get {
                return this.nombreArtistaField;
            }
            set {
                this.nombreArtistaField = value;
                this.RaisePropertyChanged("nombreArtista");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string titulo {
            get {
                return this.tituloField;
            }
            set {
                this.tituloField = value;
                this.RaisePropertyChanged("titulo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CancionSW.CancionSW")]
    public interface CancionSW {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClienteCancion.CancionSW.Exception), Action="", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteCancion.CancionSW.listarCancionesResponse listarCanciones(ClienteCancion.CancionSW.listarCancionesRequest request);
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClienteCancion.CancionSW.Exception), Action="", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClienteCancion.CancionSW.adicionarCancionResponse adicionarCancion(ClienteCancion.CancionSW.adicionarCancionRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClienteCancion.CancionSW.Exception), Action="", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteCancion.CancionSW.buscarCancionResponse buscarCancion(ClienteCancion.CancionSW.buscarCancionRequest request);
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClienteCancion.CancionSW.Exception), Action="", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClienteCancion.CancionSW.actualizarCancionResponse actualizarCancion(ClienteCancion.CancionSW.actualizarCancionRequest request);
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClienteCancion.CancionSW.Exception), Action="", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClienteCancion.CancionSW.eliminarCancionResponse eliminarCancion(ClienteCancion.CancionSW.eliminarCancionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarCanciones", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class listarCancionesRequest {
        
        public listarCancionesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarCancionesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class listarCancionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteCancion.CancionSW.cancion[] @return;
        
        public listarCancionesResponse() {
        }
        
        public listarCancionesResponse(ClienteCancion.CancionSW.cancion[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="adicionarCancion", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class adicionarCancionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteCancion.CancionSW.cancion arg0;
        
        public adicionarCancionRequest() {
        }
        
        public adicionarCancionRequest(ClienteCancion.CancionSW.cancion arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="adicionarCancionResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class adicionarCancionResponse {
        
        public adicionarCancionResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarCancion", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class buscarCancionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public buscarCancionRequest() {
        }
        
        public buscarCancionRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarCancionResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class buscarCancionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteCancion.CancionSW.cancion @return;
        
        public buscarCancionResponse() {
        }
        
        public buscarCancionResponse(ClienteCancion.CancionSW.cancion @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarCancion", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class actualizarCancionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteCancion.CancionSW.cancion arg0;
        
        public actualizarCancionRequest() {
        }
        
        public actualizarCancionRequest(ClienteCancion.CancionSW.cancion arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarCancionResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class actualizarCancionResponse {
        
        public actualizarCancionResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarCancion", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class eliminarCancionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public eliminarCancionRequest() {
        }
        
        public eliminarCancionRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarCancionResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class eliminarCancionResponse {
        
        public eliminarCancionResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CancionSWChannel : ClienteCancion.CancionSW.CancionSW, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CancionSWClient : System.ServiceModel.ClientBase<ClienteCancion.CancionSW.CancionSW>, ClienteCancion.CancionSW.CancionSW {
        
        public CancionSWClient() {
        }
        
        public CancionSWClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CancionSWClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CancionSWClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CancionSWClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteCancion.CancionSW.listarCancionesResponse ClienteCancion.CancionSW.CancionSW.listarCanciones(ClienteCancion.CancionSW.listarCancionesRequest request) {
            return base.Channel.listarCanciones(request);
        }
        
        public ClienteCancion.CancionSW.cancion[] listarCanciones() {
            ClienteCancion.CancionSW.listarCancionesRequest inValue = new ClienteCancion.CancionSW.listarCancionesRequest();
            ClienteCancion.CancionSW.listarCancionesResponse retVal = ((ClienteCancion.CancionSW.CancionSW)(this)).listarCanciones(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteCancion.CancionSW.adicionarCancionResponse ClienteCancion.CancionSW.CancionSW.adicionarCancion(ClienteCancion.CancionSW.adicionarCancionRequest request) {
            return base.Channel.adicionarCancion(request);
        }
        
        public void adicionarCancion(ClienteCancion.CancionSW.cancion arg0) {
            ClienteCancion.CancionSW.adicionarCancionRequest inValue = new ClienteCancion.CancionSW.adicionarCancionRequest();
            inValue.arg0 = arg0;
            ClienteCancion.CancionSW.adicionarCancionResponse retVal = ((ClienteCancion.CancionSW.CancionSW)(this)).adicionarCancion(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteCancion.CancionSW.buscarCancionResponse ClienteCancion.CancionSW.CancionSW.buscarCancion(ClienteCancion.CancionSW.buscarCancionRequest request) {
            return base.Channel.buscarCancion(request);
        }
        
        public ClienteCancion.CancionSW.cancion buscarCancion(int arg0) {
            ClienteCancion.CancionSW.buscarCancionRequest inValue = new ClienteCancion.CancionSW.buscarCancionRequest();
            inValue.arg0 = arg0;
            ClienteCancion.CancionSW.buscarCancionResponse retVal = ((ClienteCancion.CancionSW.CancionSW)(this)).buscarCancion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteCancion.CancionSW.actualizarCancionResponse ClienteCancion.CancionSW.CancionSW.actualizarCancion(ClienteCancion.CancionSW.actualizarCancionRequest request) {
            return base.Channel.actualizarCancion(request);
        }
        
        public void actualizarCancion(ClienteCancion.CancionSW.cancion arg0) {
            ClienteCancion.CancionSW.actualizarCancionRequest inValue = new ClienteCancion.CancionSW.actualizarCancionRequest();
            inValue.arg0 = arg0;
            ClienteCancion.CancionSW.actualizarCancionResponse retVal = ((ClienteCancion.CancionSW.CancionSW)(this)).actualizarCancion(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteCancion.CancionSW.eliminarCancionResponse ClienteCancion.CancionSW.CancionSW.eliminarCancion(ClienteCancion.CancionSW.eliminarCancionRequest request) {
            return base.Channel.eliminarCancion(request);
        }
        
        public void eliminarCancion(int arg0) {
            ClienteCancion.CancionSW.eliminarCancionRequest inValue = new ClienteCancion.CancionSW.eliminarCancionRequest();
            inValue.arg0 = arg0;
            ClienteCancion.CancionSW.eliminarCancionResponse retVal = ((ClienteCancion.CancionSW.CancionSW)(this)).eliminarCancion(inValue);
        }
    }
}
